import ScrollToTopBtn from "@/components/ScrollToTopBtn";
import SpaceCanvas from "@/components/SpaceCanvas";
import Intro from "@/components/main/Intro";
import "@/style/global.scss";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SpaceCanvas />
        {children}
      </body>
    </html>
  );
}
